# mpf-monitor

# todo
# tests
# test against the multiple versions of MPF that are supported
# load the graphics environment to make sure everything works?

language: python

python:
  - "3.4"

install:
  - pip3 install --upgrade setuptools pip twine

script:
  - python3 setup.py install;

after_success:
  - python3 setup.py sdist; python3 -m twine upload -u brianmadden -p $PYPI_PASS --skip-existing dist/*;

deploy:
  provider: pypi
  user: brianmadden
  password:
    secure: F+Pbg/DfprzBs2Jestrl5GbB3q/F65UTVJo3yAL+cyzuWcPANm+pzAMBAfOOoz1PsQbIkXJzCDDjcw9AYXBvO1z3zMUvuFU1UTpf1Ezxt3PdnkDDwBYTj3VSexwyKqC82myARCXskD+aiD7ZR4OzrBelnM2K9qeXbhobMIntCJa3y7OF4rln8bJs1FogQg3+OMadc4XbFL5iFQdePzjqVii61uFfhTZDEiW+wNyWcB0h4R1Rf0TzN0OMlCBKJTRBXFUR8DtQ0wNA+mg3KaxPitrSv6yN3ZY4f+U2Mad9SYZamSY+MpOeX5rejPSJZ1faqn+JfIGPcbARchooC5v/bB6wzg7MSPHh0jbE6UIbJr8QKwe8T1gVPc0Vz+EYBhBp/474jmlrBvb99Ap9QbvAIluKeNbHoTF2fvyQIZUzJV0f9lw/cVwYDQMLDsiKc7SVNiH5jh+Ms0icpR+Qs22e5R0xkLWajGbkIQxUKlAoUiFi0hxInkXfrropYqkt1UnZXtswuCpV46uBQXc1cox5flczbFezCUprCG6dWUUsbqfxnwemz9PQESigThdhDfLFTmDk5WvI5qw7a2pTCRkvAq3fr6081FBYJSflHyM/ktCpgKmBagckFOTWFu5PCUl0dnk8po7cmxTaLFlIPW22ssL6iPfq+zc70bhNgvxFPt8=
  on:
    repo: missionpinball/mpf-monitor
